# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-01 19:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_remove_post_title1'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=255)),
                ('content', models.CharField(max_length=1000)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('slug', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.Post')),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
    ]
