# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-07 20:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20170802_1908'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='slug',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='blog.Post'),
        ),
    ]
